apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: hunt-internal-trust-bundle
  # this is a cluster scoped resource
spec:
  sources:
  - useDefaultCAs: false
  - secret:
      name: hunt-internal-certificate-authority
      key: tls.crt
      # this must be in the "trust" namespace, which is defined in the trust-manager helm chart values
  - configMap:
      name: hunt-internal-certificate-authority-previous
      key: tls.crt
      # this must be in the "trust" namespace, which is defined in the trust-manager helm chart values
  target:
    configMap:
      key: ca.crt
      # name: matches the metadata.name
      # this config map is created in every namespace

# bootstrap process:
# 1. cert-manager: creates the hunt-internal-certificate-authority certificate and secret
# 2. trust-manager: reads the hunt-internal-certificate-authority secret and gets the tls.crt key
# 3. human: manually creates a config map called hunt-internal-certificate-authority-previous with the key/value pair equal to the tls.crt key in the hunt-internal-certificate-authority secret
# 3.A. human: command: kubectl create configmap hunt-internal-certificate-authority-previous -n cert-manager --from-literal=tls.crt="$(kubectl get secrets hunt-internal-certificate-authority -n cert-manager -o jsonpath='{.data.tls\.crt}' | base64 --decode)"
# 4. trust-manager: creates the trust bundle. (both key/value pairs should be identical)

# certificate rotation:
# 1. cert-manager: creates the new hunt-internal-certificate-authority certificate and secret automatically once the renew time comes
# 2. trust-manager: updates the trust bundle with the new key/value pair. (the key/value pairs will no longer be identical in the trust bundle)
# 3. human: monitors the environment and updates the various applications to use the updated trust bundle.
# 4. human: once all applications are updated and using the new trust bundle, the human updates hunt-internal-certificate-authority-previous to have the same key/value pair as hunt-internal-certificate-authority.
# 5. trust-manager: updates the trust bundle. (both key/value pairs should be identical)
