---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 12h
  url: https://istio-release.storage.googleapis.com/charts
...
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: istio-base
  namespace: flux-system
spec:
  chart: base
  version: "1.29.x"
  sourceRef:
    kind: HelmRepository
    name: istio
  interval: 24h
  reconcileStrategy: ChartVersion
...
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: istio-istiod
  namespace: flux-system
spec:
  chart: istiod
  version: "1.29.x"
  sourceRef:
    kind: HelmRepository
    name: istio
  interval: 24h
  reconcileStrategy: ChartVersion
...
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  chart: cni
  version: "1.29.x"
  sourceRef:
    kind: HelmRepository
    name: istio
  interval: 24h
  reconcileStrategy: ChartVersion
...
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: istio-ztunnel
  namespace: flux-system
spec:
  chart: ztunnel
  version: "1.29.x"
  sourceRef:
    kind: HelmRepository
    name: istio
  interval: 24h
  reconcileStrategy: ChartVersion
...
