---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-admin-credentials
  namespace: authentik
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-admin-credentials # secret to be created
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: password # secret key to be managed. aka the key name inside the new secret
    remoteRef:
      key: authentik-postgres-admin-credentials # provider key. aka the path (the part after secret/) to the secret in openbao
      property: password # provider key property. aka the key name within that secret in openbao
  - secretKey: username # secret key to be managed. aka the key name inside the new secret
    remoteRef:
      key: authentik-postgres-admin-credentials # provider key. aka the path (the part after secret/) to the secret in openbao
      property: username # provider key property. aka the key name within that secret in openbao
...
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-app-credentials
  namespace: authentik
spec:
  refreshInterval: 1m0s # this needs to match postgres operator refresh interval too.
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-app-credentials # secret to be created
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: password # secret key to be managed. aka the key name inside the new secret
    remoteRef:
      key: authentik-postgres-app-credentials # provider key. aka the path (the part after secret/) to the secret in openbao
      property: password # provider key property. aka the key name within that secret in openbao
  - secretKey: username # secret key to be managed. aka the key name inside the new secret
    remoteRef:
      key: authentik-postgres-app-credentials # provider key. aka the path (the part after secret/) to the secret in openbao
      property: username # provider key property. aka the key name within that secret in openbao
...
