---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-postgres-admin-credentials
  namespace: external-secrets
spec:
  refreshInterval: 6h0m0s
  secretStoreRefs:
  - name: openbao
    kind: ClusterSecretStore
  selector:
    generatorRef: # must be in the same namespace as this pushsecret
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: long-complex-password
  template:
    engineVersion: v2
    data:
      password: "{{ .password | toString }}" # password is the property in the generator output
      username: admin
  data:
  - match:
      remoteRef:
        remoteKey: authentik-postgres-admin-credentials
...
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-postgres-app-credentials
  namespace: external-secrets
spec:
  refreshInterval: 6h0m0s
  secretStoreRefs:
  - name: openbao
    kind: ClusterSecretStore
  selector:
    generatorRef: # must be in the same namespace as this pushsecret
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: long-complex-password
  template:
    engineVersion: v2
    data:
      password: "{{ .password | toString }}" # password is the property in the generator output
      username: app
  data:
  - match:
      remoteRef:
        remoteKey: authentik-postgres-app-credentials
...
