apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-cluster-lab
  namespace: flux-system
spec:
  interval: 15m
  url: https://github.com/hausteen/kubernetesApplicationsLab.git
  ref:
    branch: main
