---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  install:
    crds: Create
    createNamespace: false
    serverSideApply: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: Create
    serverSideApply: enabled
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  releaseName: base
  targetNamespace: istio-system
  chartRef:
    kind: HelmChart
    name: istio-base
    namespace: flux-system
...
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: flux-system
spec:
  dependsOn:
  - name: istio-base
    namespace: flux-system
  interval: 15m
  timeout: 5m
  install:
    crds: Skip
    createNamespace: false
    serverSideApply: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: Skip
    serverSideApply: enabled
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  releaseName: istiod
  targetNamespace: istio-system
  chartRef:
    kind: HelmChart
    name: istio-istiod
    namespace: flux-system
  values:
    profile: ambient
    seccompProfile:
      type: RuntimeDefault
...
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  dependsOn:
  - name: istio-istiod
    namespace: flux-system
  interval: 15m
  timeout: 5m
  install:
    crds: Skip
    createNamespace: false
    serverSideApply: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: Skip
    serverSideApply: enabled
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  releaseName: cni
  targetNamespace: istio-system
  chartRef:
    kind: HelmChart
    name: istio-cni
    namespace: flux-system
  values:
    profile: ambient
    seccompProfile:
      type: RuntimeDefault
...
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: flux-system
spec:
  dependsOn:
  - name: istio-cni
    namespace: flux-system
  interval: 15m
  timeout: 5m
  install:
    crds: Skip
    createNamespace: false
    serverSideApply: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: Skip
    serverSideApply: enabled
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  releaseName: ztunnel
  targetNamespace: istio-system
  chartRef:
    kind: HelmChart
    name: istio-ztunnel
    namespace: flux-system
...
