apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- resources/helm-controller.yaml

# https://docs.nginx.com/nginx-gateway-fabric/install/helm/
# https://github.com/nginx/nginx-gateway-fabric/tree/main/charts/nginx-gateway-fabric
# https://docs.nginx.com/nginx-gateway-fabric/overview/gateway-api-compatibility/
