apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-lab
  namespace: cnpg-system
spec:
  secretName: keycloak-lab
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  issuerRef:
    name: hunt-internal
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  isCA: false
  subject:
    countries:
    - usa
    organizations:
    - hunt
  dnsNames:
  - keycloak-lab-rw
  - keycloak-lab-rw.cnpg-system
  - keycloak-lab-rw.cnpg-system.svc
  - keycloak-lab-rw.cnpg-system.svc.local
  - keycloak-lab-r
  - keycloak-lab-r.cnpg-system
  - keycloak-lab-r.cnpg-system.svc
  - keycloak-lab-r.cnpg-system.svc.local
  - keycloak-lab-ro
  - keycloak-lab-ro.cnpg-system
  - keycloak-lab-ro.cnpg-system.svc
  - keycloak-lab-ro.cnpg-system.svc.local
  duration: 720h # 30 days * 24 hours
  renewBefore: 120h # 5 days before it ends. 5 days * 24 hours
