apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  secretName: authentik-postgres-certificate
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  issuerRef:
    name: hunt-internal
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 256
  isCA: false
  subject:
    countries:
    - usa
    organizations:
    - hunt
  dnsNames:
  - authentik-rw
  - authentik-rw.authentik
  - authentik-rw.authentik.svc
  - authentik-rw.authentik.svc.cluster.local
  - authentik-r
  - authentik-r.authentik
  - authentik-r.authentik.svc
  - authentik-r.authentik.svc.cluster.local
  - authentik-ro
  - authentik-ro.authentik
  - authentik-ro.authentik.svc
  - authentik-ro.authentik.svc.cluster.local
  duration: 720h # 30 days * 24 hours
  renewBefore: 120h # 5 days before it ends. 5 days * 24 hours
