apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  instances: 3
  certificates:
    serverCASecret: authentik-postgres-certificate # this must be a secret. a configmap wont work here... put in a github feature request for configmaps
    serverTLSSecret: authentik-postgres-certificate
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: authentik-postgres-app-credentials
  storage:
    pvcTemplate:
      accessModes:
      - ReadWriteOncePod
      resources:
        requests:
          storage: 5Gi
      storageClassName: no-replication
      volumeMode: Filesystem
  logLevel: info
  managed:
    roles:
    - name: admin
      login: true
      superuser: true
      passwordSecret:
        name: authentik-postgres-admin-credentials
