apiVersion: v1
kind: Namespace
metadata:
  name: nginx-gateway-fabric
  # labels:
    # istio.io/dataplane-mode: ambient
    # istio.io/use-waypoint: waypoint

# this is the control plane namespace for nginx gateway fabric.
# try not to install gateway api stuff here; unless its cluster wide.
# I have decided that the data plane namespace is 'gateway-api'
