apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  install:
    crds: Create
    createNamespace: false
    serverSideApply: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: Create
    serverSideApply: enabled
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  releaseName: nginx-gateway-fabric
  targetNamespace: nginx-gateway-fabric
  chartRef:
    kind: OCIRepository
    name: nginx-gateway-fabric
    namespace: flux-system
  values:
    nginxGateway:
      config:
        logging:
          level: debug
      productTelemetry:
        enable: false
      gwAPIExperimentalFeatures:
        enable: true
      gatewayClassName: nginx-gateway-fabric
      replicas: 1
    nginx:
      replicas: 2
      service:
        externalTrafficPolicy: Cluster
      config:
        logging:
          agentLevel: debug
          errorLevel: debug
      debug: true
