apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/certificate.yaml
# - resources/gateway-class.yaml # not needed when using nginx-gateway-fabric
- resources/nginx-proxy.yaml
- resources/gateway.yaml
- resources/http-route.yaml
