apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/source-controller.yaml
- resources/kustomize-controller.yaml

# https://docs.nginx.com/nginx-gateway-fabric/overview/gateway-api-compatibility/
