---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-lab-admin
  namespace: cnpg-system
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: keycloak-lab-admin # secret to be created
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: password # secret key to be managed. aka the key name inside the new secret
    remoteRef:
      key: keycloak-lab-admin # provider key. aka the path (the part after secret/) to the secret in openbao
      property: password # provider key property. aka the key name within that secret in openbao
  - secretKey: username # secret key to be managed. aka the key name inside the new secret
    remoteRef:
      key: keycloak-lab-admin # provider key. aka the path (the part after secret/) to the secret in openbao
      property: username # provider key property. aka the key name within that secret in openbao
...
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-lab-app
  namespace: cnpg-system
spec:
  refreshInterval: 1m0s # this needs to match postgres operator refresh interval too.
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: keycloak-lab-app # secret to be created
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: password # secret key to be managed. aka the key name inside the new secret
    remoteRef:
      key: keycloak-lab-app # provider key. aka the path (the part after secret/) to the secret in openbao
      property: password # provider key property. aka the key name within that secret in openbao
  - secretKey: username # secret key to be managed. aka the key name inside the new secret
    remoteRef:
      key: keycloak-lab-app # provider key. aka the path (the part after secret/) to the secret in openbao
      property: username # provider key property. aka the key name within that secret in openbao
...
