apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: long-complex-password
  namespace: external-secrets
spec:
  length: 128
  noUpper: false
  allowRepeat: true
  # symbolCharacters: defaults to ~!@#$%^&*()_+`-={}|[]\:"<>?,./
  # digits: number defaults to 25 percent of the length
  # symbols: number defaults to 25 percent of the length
  # encoding: default is raw
