apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hunt-internal-certificate-authority/issuer-self-signed.yaml
- hunt-internal-certificate-authority/certificate-hunt-internal-certificate-authority.yaml
- hunt-internal-certificate-authority/cluster-issuer-hunt-internal.yaml
