apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  install:
    crds: Create
    createNamespace: false
    serverSideApply: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: Create
    serverSideApply: enabled
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  releaseName: external-secrets-operator
  targetNamespace: external-secrets
  chartRef:
    kind: HelmChart
    name: external-secrets-operator
    namespace: flux-system
  values:
    log:
      level: info
    serviceAccount:
      create: true
      name: external-secrets-operator
    webhook:
      extraArgs:
        tls-min-version: "1.3"
