apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  # labels:
    # istio.io/dataplane-mode: ambient
    # istio.io/use-waypoint: waypoint
# this namespace is created by opentofu since we need to create the secrets
# for the authentik server secret key and initial admin password hash.
