apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: "https://openbao.openbao.svc.cluster.local:8200"
      path: secret
      version: v1
      checkAndSet:
        required: false
      caProvider:
        type: ConfigMap
        name: hunt-internal-trust-bundle
        key: ca.crt
        namespace: external-secrets
      auth:
        kubernetes:
          mountPath: kubernetes
          role: kv1-rw
          serviceAccountRef:
            name: external-secrets-operator
            namespace: external-secrets
            audiences:
            - openbao
  # conditions:
  # - namespaces:
  #   - external-secrets
  #   - openbao
  #   - cnpg-system
  #   - authentik
  #   - keycloak
