apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/authentik.yaml
- resources/cert-manager.yaml
- resources/cnpg-system.yaml
- resources/coredns.yaml
- resources/external-secrets.yaml
- resources/gateway-api.yaml
- resources/istio-system.yaml
- resources/keycloak.yaml
- resources/longhorn-system.yaml
- resources/nginx-gateway-fabric.yaml
- resources/openbao.yaml
- resources/trust-manager.yaml
