---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-install-1
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cilium/install-1/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces-install
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/namespaces/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-gateway-fabric-pre-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install-1
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/nginx-gateway-fabric/pre-install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-install-2
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cilium/install-2/overlays/lab
...
