apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  install:
    crds: Create
    createNamespace: false
    serverSideApply: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: Create
    serverSideApply: enabled
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  releaseName: coredns
  targetNamespace: coredns
  chartRef:
    kind: HelmChart
    name: coredns
    namespace: flux-system
  values:
    image:
      tag: "1.14.3" # the helm chart pulls an out of date coredns image so i declare the coredns image to pull. This is the true 'version'.
    isClusterService: false
    replicaCount: 2
    service:
      name: coredns
    securityContext: # the helm values doesn't show that this is possible, but it is. The chart pulls this whole block in so as long as its a valid security context, it will work.
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - ALL
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      runAsUser: 1000
      runAsGroup: 1000
    servers: # these servers are converted into a single config map named 'coredns'. the config map is mounted read/write as a volume into the pod at /etc/coredns
    - zones:
      - zone: hunt.internal
        use_tcp: true
      port: 53
      plugins:
      - name: cache
        parameters: 30
      - name: errors
      - name: file
        parameters: /etc/coredns/hunt.internal.db # filename matches zoneFiles.filename
      - name: auto
        configBlock: |-
          directory /etc/coredns (.*)\.db {1}
          reload 30s
      - name: loadbalance
      - name: log
      - name: loop
      - name: ready
      - name: reload
    - zones:
      - zone: .
        use_tcp: true
      port: 53
      plugins:
      - name: cache
        parameters: 30
      - name: errors
      - name: forward
        parameters: . 1.1.1.1
      - name: loadbalance
      - name: log
      - name: loop
      - name: ready
      - name: reload
      - name: health
        configBlock: |-
          lameduck 10s
    zoneFiles:
    - filename: hunt.internal.db
      domain: hunt.internal
      contents: |
        $TTL 30 ; default TTL
        $ORIGIN hunt.internal. ; base domain name
        ; start of authority resource record defining the key characteristics of the zone (domain)
        @ IN SOA ns1.hunt.internal. placeholder-email.hunt.internal. (
          1     ; serial number - change this number each time a change is made or else coredns won't pick up the change
          60    ; refresh       - every minute
          300   ; update retry  - every 5 minutes
          86400 ; expiry        - 24 hours
          30    ; minimum ttl   - 1 hour
          )
                 IN NS ns1.hunt.internal. ; name server resource record for the domain
        ns1      IN A 192.168.30.2
        longhorn IN A 192.168.30.2
        openbao  IN A 192.168.30.2
        hubble   IN A 192.168.30.2
      # dont forget... serial number - change this number each time a change is made or else coredns won't pick up the change
