apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: enable-strict-mutual-tls
  namespace: default
spec:
  mtls:
    mode: STRICT

# this enables strict mutual tls for the given namespace
# do NOT add these namespaces to the service mesh: kube-system, flux-system, istio-system
