---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces-install
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/namespaces/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-gateway-fabric-pre-install
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/nginx-gateway-fabric/pre-install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-install
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cilium/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cert-manager/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/longhorn/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-gateway-fabric-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  - name: nginx-gateway-fabric-pre-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/nginx-gateway-fabric/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/coredns/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/istio/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/external-secrets-operator/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnativepg-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cloudnativepg/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-post-install-1
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cilium/post-install-1/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/trust-manager/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-post-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cert-manager/post-install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-post-install
  namespace: flux-system
spec:
  dependsOn:
  - name: istio-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/istio/post-install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-gateway-fabric-post-install
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager-post-install
    namespace: flux-system
  - name: nginx-gateway-fabric-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/nginx-gateway-fabric/post-install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager-post-install
  namespace: flux-system
spec:
  dependsOn:
  - name: trust-manager-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/trust-manager/post-install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-post-install
  namespace: flux-system
spec:
  dependsOn:
  - name: coredns-install
    namespace: flux-system
  - name: nginx-gateway-fabric-post-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/coredns/post-install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-post-install-2
  namespace: flux-system
spec:
  dependsOn:
  - name: cilium-install
    namespace: flux-system
  - name: nginx-gateway-fabric-post-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/cilium/post-install-2/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-post-install
  namespace: flux-system
spec:
  dependsOn:
  - name: longhorn-install
    namespace: flux-system
  - name: nginx-gateway-fabric-post-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/longhorn/post-install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao-install
  namespace: flux-system
spec:
  dependsOn:
  - name: longhorn-install
    namespace: flux-system
  - name: trust-manager-post-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/openbao/install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao-post-install
  namespace: flux-system
spec:
  dependsOn:
  - name: openbao-install
    namespace: flux-system
  - name: nginx-gateway-fabric-post-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/openbao/post-install/overlays/lab
...
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator-post-install
  namespace: flux-system
spec:
  dependsOn:
  - name: external-secrets-operator-install
    namespace: flux-system
  - name: openbao-install
    namespace: flux-system
  - name: trust-manager-post-install
    namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  path: manifests/external-secrets-operator/post-install/overlays/lab
...
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: <>
#   namespace: flux-system
# spec:
#   dependsOn:
#   - name: <>
#     namespace: flux-system
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   interval: 10m
#   timeout: 5m
#   prune: true
#   wait: true
#   path: <>
# ...
