apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-crds
  namespace: flux-system
spec:
  interval: 6h
  url: https://github.com/kubernetes-sigs/gateway-api.git
  sparseCheckout:
  - config/crd/experimental
  # - config/crd/standard
  ref:
    tag: v1.5.1

# be careful of gateway api version requirements for nginx gateway fabric and other applications
