apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: front-door
  namespace: gateway-api
spec:
  ipFamily: ipv4
  kubernetes:
    service:
      externalTrafficPolicy: Cluster
      patches:
      - type: StrategicMerge
        value:
          metadata:
            annotations:
              lbipam.cilium.io/ips: 192.168.30.3
              # metallb.io/loadBalancerIPs: 192.168.30.3
