# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: waypoint-gateway-options
#   namespace: cert-manager
# data:
#   deployment: |
#     spec:
#       template:
#         spec:
#           securityContext:
#             seccompProfile:
#               type: RuntimeDefault
# ...
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: waypoint
#   namespace: cert-manager
#   labels:
#     istio.io/waypoint-for: service # https://istio.io/latest/docs/ambient/usage/waypoint/#waypoint-traffic-types
# spec:
#   gatewayClassName: istio-waypoint
#   infrastructure:
#     parametersRef:
#       kind: ConfigMap
#       name: waypoint-gateway-options
#   listeners:
#   - name: mesh
#     port: 15008
#     protocol: HBONE
# ...
# # I'm not sure yet on how the front-door gateway (nginx-gateway-fabric gateway) is supposed to work with istio waypoints.
