---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coredns
  namespace: flux-system
spec:
  interval: 12h
  url: https://coredns.github.io/helm
...
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: coredns
  namespace: flux-system
spec:
  chart: coredns
  version: "1.46.x"
  sourceRef:
    kind: HelmRepository
    name: coredns
  interval: 24h
  reconcileStrategy: ChartVersion
...
